/* P0 credibility — fetch split gzip-b64 then expand */
const __base = new URL("./", import.meta.url);
const __parts = await Promise.all([0,1].map(i => fetch(new URL(`charts.b64.${i}`, __base)).then(r => r.text())));
const __b64 = __parts.join("").replace(/\s+/g, "");
const __bin = Uint8Array.from(atob(__b64), (c) => c.charCodeAt(0));
const __code = await new Response(new Blob([__bin]).stream().pipeThrough(new DecompressionStream("gzip"))).text();
const __rewritten = __code.replace(/(from\s+["'])(\.\/[^"']+)(["'])/g, (_m,a,rel,b)=>a+new URL(rel,__base).href+b);
const __mod = await import(URL.createObjectURL(new Blob([__rewritten], { type: "text/javascript" })));
export const filterSeriesByWindow = __mod.filterSeriesByWindow;
export const summarizeWindow = __mod.summarizeWindow;
export const findNearestSeriesPoint = __mod.findNearestSeriesPoint;
export const extractFactorBreakdown = __mod.extractFactorBreakdown;
export const extractFactorScore = __mod.extractFactorScore;
export const seriesHasFactorScores = __mod.seriesHasFactorScores;
export const getSeriesVisibility = __mod.getSeriesVisibility;
export const getHideLowQuality = __mod.getHideLowQuality;
export const setHideLowQuality = __mod.setHideLowQuality;
export const setSeriesVisibility = __mod.setSeriesVisibility;
export const getHistoryChart = __mod.getHistoryChart;
export const getIndicatorFocus = __mod.getIndicatorFocus;
export const clearIndicatorFocus = __mod.clearIndicatorFocus;
export const setIndicatorFocus = __mod.setIndicatorFocus;
export const resetHistoryZoom = __mod.resetHistoryZoom;
export const renderHistoryChart = __mod.renderHistoryChart;
